# Generated by Django 2.2 on 2021-08-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy_app', '0005_auto_20210826_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherstrip',
            old_name='other_created_at',
            new_name='othercreated_at',
        ),
        migrations.RenameField(
            model_name='otherstrip',
            old_name='other_end_date',
            new_name='otherend_date',
        ),
        migrations.RenameField(
            model_name='otherstrip',
            old_name='other_start_date',
            new_name='otherstart_date',
        ),
        migrations.RenameField(
            model_name='otherstrip',
            old_name='other_updated_at',
            new_name='otherupdated_at',
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
