# Generated by Django 2.2 on 2021-08-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy_app', '0006_auto_20210826_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OthersTrip',
        ),
    ]
