# Generated by Django 2.2 on 2021-08-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='Authors', to='books_authors_app.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='NotesDefault', max_length=45),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(verbose_name=''),
        ),
    ]
