# Generated by Django 2.2 on 2021-08-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_remove_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='Authors', to='books_authors_app.Book'),
        ),
    ]
