# Generated by Django 2.2 on 2021-08-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
