# Generated by Django 2.2 on 2021-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comment',
            field=models.TextField(default='null=True'),
            preserve_default=False,
        ),
    ]
