# Generated by Django 2.2 on 2021-08-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20210816_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='comment',
        ),
    ]
