# Generated by Django 2.2 on 2021-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20210812_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
