# Generated by Django 2.2 on 2021-08-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_auto_20210813_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
