# Generated by Django 2.2 on 2021-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_auto_20210819_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='quotes_app.User'),
        ),
    ]
